on:
  push:
    tags:
      - v*
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          # PRs just build the image to confirm they can
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/bmillwood/flexiprocity:${{ github.sha }}
          # default scope is branch name, this allows branches to start their
          # cache with the one from main
          cache-from: |
            type=gha
            type=gha,scope=main
          cache-to: type=gha,mode=max
