on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/db-test.yml
      - schema/test.sh
      - schema/create-users.sh
      - schema/**.sql

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    services:
      # https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers
      postgres:
        image: ghcr.io/bmillwood/flexiprocity/postgres-pgtap:16@sha256:9d60880bc2bd7337b5066bba5370efbfe0aa7a71675e0237a923653f023b2bbc
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      PGHOST: localhost
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: ./test.sh
        working-directory: schema
