on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/db-test.yml
      - schema/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    services:
      # https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers
      postgres:
        image: ghcr.io/bmillwood/flexiprocity/postgres-pgtap:16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      PGHOST: localhost
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: ./test.sh
        working-directory: schema
