on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      PGHOST: localhost
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v6
      - run: ./apply.sh
        working-directory: schema
