on:
  schedule:
  - cron: "30 17 * * 5" # Friday afternoon
  workflow_dispatch:
  pull_request:
    paths:
    - .github/renovate.json
    - .github/workflows/renovate.yml

jobs:
  upgrade-dependencies:
    uses: bmillwood/renovateconfig/.github/workflows/renovate.yml@6f8c265fdfe937a94ccc63a226077b4dc983f7dd # main
    secrets: inherit
