on:
  schedule:
  - cron: "30 17 * * 5" # Friday afternoon
  workflow_dispatch:
  pull_request:
    paths:
    - .github/renovate.json
    - .github/workflows/renovate.yml

jobs:
  upgrade-dependencies:
    uses: bmillwood/renovateconfig/.github/workflows/renovate.yml@920c1bdc102b0c8328dccba9287d9a3ac785199c # main
    secrets: inherit
